# Hugo variables
# 
baseurl = "https://example.org/"
languageCode = "en-us"
title = "Hugo Bootstrap v4 Blog"
theme = "hugo-theme-bootstrap4-blog"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
#googleAnalytics = "UA-123-45"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Link 1"
  url = "https://example.com"

[[menu.sidebar]]
  name = "Link 2"
  url = "https://example.org"

# Theme variables
#
[params]
  # Site author
  author = "Your Name"

  # Description/subtitle for homepage (can be Markdown)
  description = "A simple Hugo theme based on the Bootstrap v4 blog example."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "username"

  [params.sharingicons]
    # Hide the sharing icons on posts? (Default: false)
    hide = false

    # Optionally, set any of these to false to hide them:
    #facebook = true
    #googleplus = true
    #linkedin = true
    #twitter = true

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
